# Generated by Django 3.2 on 2021-07-25 16:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, upload_to=users.models.user_avatar_image_path),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='about_user',
            field=models.TextField(blank=True),
        ),
    ]
